defaults:
  - override hydra/sweeper: optuna

pipeline:
  random_seed: 20230214

  data:
    train_path: ../data/train.csv
    test_path: ../data/test.csv

  model:
    # _target_: catboost.CatBoostRegressor
    # random_seed: ${..random_seed}
    _target_: lightgbm.LGBMRegressor
    random_state: ${..random_seed}
    n_jobs: -1

  feature_generator:
    _target_: data.feature_engineering.FeatureGenerator
    columns_to_remove: [product_type, district_name, timestamp]

  cv:
    _partial_: true
    _target_: validation.timeline_val.train_test_split
    n: 5
    test_size: 3239
    shuffle: true
    random_seed: ${..random_seed}
    val_type: growing-window

  metric:
    _partial_: true
    _target_: sklearn.metrics.mean_squared_log_error
    squared: false

mlflow:
  runname: "test"

hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: minimize
    study_name: mlflow.runname
    storage: null
    n_trials: 20
    n_jobs: 1
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: ${pipeline.random_seed}
      n_startup_trials: 10
    params:
      # +pipeline.model.depth: range(4, 16)
      +pipeline.model.max_depth: range(4, 16)
      # pipeline.model.iterations: range(1000, 2000)
    #   pipeline.model.depth:
    #     type: int
    #     low: 4
    #     high: 16
    #   pipeline.model.iterations:
    #     type: int
    #     low: 500
    #     high: 1500

    # seed: pipeline.random_seed
