defaults:
  - _self_
  - data: competition_data
  - feature_generator: feature_generator
  - cv: timeline_cv
  - metric: msle
  - model: lightgbm
  - search_space@hydra.sweeper.params: lightgbm
  - override hydra/sweeper: optuna

general:
  runname: "lgbm_fe_0"
  random_seed: 20230214
  
hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: minimize
    study_name: mlflow.runname
    storage: null
    n_trials: 100
    n_jobs: 1
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: ${general.random_seed}
      n_startup_trials: 20
